header:
  license:
    spdx-id: Apache-2.0
    # The copyright owner
    copyright-owner: ClrSlate Tech labs Private Limited

  # The paths to check
  paths:
    - '**/*.cs'
    - '**/*.md'

  # The paths to ignore
  paths-ignore:
    - 'LICENSE'
    - 'NOTICE'
    - 'README.md'
    - 'CONTRIBUTING.md'
    - 'CODE_OF_CONDUCT.md'
    - 'docs/'
    - '.github/'
    - 'artifacts/'
    - '**/bin/**'
    - '**/obj/**'
    - 'node_modules/'
    - 'TestResults/'
