{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  labels:
    name: {{ .Release.Name }}-vs
spec:
  hosts:
  - {{ .Values.ingress.domain.sub }}.{{ .Values.ingress.domain.base }}
  gateways:
  - {{ .Values.ingress.gateway}}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: 80
    appendHeaders:
        "x-forwarded-proto": "https"
        "x-forwarded-port": "443"
{{- end }}